service: api-sense #Name of your App

provider:
 name: aws
 runtime: nodejs16.x # Node JS version
 memorySize: 512
 timeout: 15
 stage: develop
 region: us-east-2 # AWS region

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY {proxy+}
     - http: ANY /